name: "Python Linter"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: "Python Linter"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "source"
          mypy-options: "--ignore-missing-imports --show-error-codes"